openapi: 3.0.3
info:
  title: Meerkat API
  version: 0.0.1
  description: |
    This API is only used by Meerkat frontend application for mocking purposes.

servers:
  - url: http://localhost:8080/
    description: Local development server

externalDocs:
  url: https://swagger.io/specification/
  description: Find more information about OAS3.0 standard.

tags:
  - name: Sector
    description: API for services related managing manufacturing sectors.
  - name: FormData
    description: API for services related handling user form input.

paths:
  /sectors:
    get:
      operationId: getSectors
      tags:
        - Sector
      summary: Queries all available sectors for selection.
      description:
        Selects all sectors stored in database and returns them as an array of sectors.
      responses:
        '200':
          description: Successful query returns an array of sectors.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sector'

  /form-data:
    post:
      operationId: saveFormData
      tags:
        - FormData
      summary: Saves user form data input.
      description:
        Parses and validates user form data input and saves it into the database.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/FormData'
      responses:
        '200':
          description: Successfully saved form data.

    get:
      operationId: getSavedFormData
      tags:
        - FormData
      responses:
        '200':
          description: Successful query returns an array of sectors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormData'

components:
  schemas:
    Sector:
      type: object
      properties:
        value:
          type: integer
          description: Sector integer value code
        name:
          type: string
          description: Sector name

    FormData:
      type: object
      required:
        - name
        - sector
        - agreement
      properties:
        name:
          type: string
          minimum: 1
          description: User name as text input value.
        sector:
          type: integer
          description: Sector value.
        agreement:
          type: boolean
          description: Agreement to form terms and policies.
